// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginData     *LoginData             `protobuf:"bytes,1,opt,name=login_data,json=loginData,proto3" json:"login_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetLoginData() *LoginData {
	if x != nil {
		return x.LoginData
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	NewUser       *User                  `protobuf:"bytes,2,opt,name=new_user,json=newUser,proto3" json:"new_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UpdateUserRequest) GetNewUser() *User {
	if x != nil {
		return x.NewUser
	}
	return nil
}

type UpdateUserAvatarRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UploadDir        string                 `protobuf:"bytes,1,opt,name=upload_dir,json=uploadDir,proto3" json:"upload_dir,omitempty"`
	HashedAvatarName string                 `protobuf:"bytes,2,opt,name=hashed_avatar_name,json=hashedAvatarName,proto3" json:"hashed_avatar_name,omitempty"`
	AvatarFile       []byte                 `protobuf:"bytes,3,opt,name=avatar_file,json=avatarFile,proto3" json:"avatar_file,omitempty"`
	User             *User                  `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateUserAvatarRequest) Reset() {
	*x = UpdateUserAvatarRequest{}
	mi := &file_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAvatarRequest) ProtoMessage() {}

func (x *UpdateUserAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAvatarRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserAvatarRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserAvatarRequest) GetUploadDir() string {
	if x != nil {
		return x.UploadDir
	}
	return ""
}

func (x *UpdateUserAvatarRequest) GetHashedAvatarName() string {
	if x != nil {
		return x.HashedAvatarName
	}
	return ""
}

func (x *UpdateUserAvatarRequest) GetAvatarFile() []byte {
	if x != nil {
		return x.AvatarFile
	}
	return nil
}

func (x *UpdateUserAvatarRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfileRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type FavoriteMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	MovieId       string                 `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteMovieRequest) Reset() {
	*x = FavoriteMovieRequest{}
	mi := &file_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteMovieRequest) ProtoMessage() {}

func (x *FavoriteMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteMovieRequest.ProtoReflect.Descriptor instead.
func (*FavoriteMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *FavoriteMovieRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *FavoriteMovieRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type FavoriteActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteActorRequest) Reset() {
	*x = FavoriteActorRequest{}
	mi := &file_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteActorRequest) ProtoMessage() {}

func (x *FavoriteActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteActorRequest.ProtoReflect.Descriptor instead.
func (*FavoriteActorRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *FavoriteActorRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *FavoriteActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type User struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar         string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	HashedPassword string                 `protobuf:"bytes,6,opt,name=hashed_password,json=hashedPassword,proto3" json:"hashed_password,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *User) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

type Profile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Username        string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Avatar          string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MovieCollection []*Movie               `protobuf:"bytes,5,rep,name=movie_collection,json=movieCollection,proto3" json:"movie_collection,omitempty"`
	Actors          []*Person              `protobuf:"bytes,6,rep,name=actors,proto3" json:"actors,omitempty"`
	Reviews         []*Review              `protobuf:"bytes,7,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *Profile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Profile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Profile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Profile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Profile) GetMovieCollection() []*Movie {
	if x != nil {
		return x.MovieCollection
	}
	return nil
}

func (x *Profile) GetActors() []*Person {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *Profile) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type LoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginData) Reset() {
	*x = LoginData{}
	mi := &file_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginData) ProtoMessage() {}

func (x *LoginData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginData.ProtoReflect.Descriptor instead.
func (*LoginData) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *LoginData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Username         string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password         string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	RepeatedPassword string                 `protobuf:"bytes,3,opt,name=repeated_password,json=repeatedPassword,proto3" json:"repeated_password,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterData) Reset() {
	*x = RegisterData{}
	mi := &file_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterData) ProtoMessage() {}

func (x *RegisterData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterData.ProtoReflect.Descriptor instead.
func (*RegisterData) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterData) GetRepeatedPassword() string {
	if x != nil {
		return x.RepeatedPassword
	}
	return ""
}

type Movie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PreviewUrl    string                 `protobuf:"bytes,3,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"`
	Duration      string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,5,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Rating        float64                `protobuf:"fixed64,6,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *Movie) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *Movie) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Movie) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Movie) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type Person struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName        string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	EnFullName      string                 `protobuf:"bytes,3,opt,name=en_full_name,json=enFullName,proto3" json:"en_full_name,omitempty"`
	Photo           string                 `protobuf:"bytes,4,opt,name=photo,proto3" json:"photo,omitempty"`
	About           string                 `protobuf:"bytes,5,opt,name=about,proto3" json:"about,omitempty"`
	Sex             string                 `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	Growth          string                 `protobuf:"bytes,7,opt,name=growth,proto3" json:"growth,omitempty"`
	Birthday        string                 `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Death           string                 `protobuf:"bytes,9,opt,name=death,proto3" json:"death,omitempty"`
	Career          string                 `protobuf:"bytes,10,opt,name=career,proto3" json:"career,omitempty"`
	Genres          string                 `protobuf:"bytes,11,opt,name=genres,proto3" json:"genres,omitempty"`
	TotalFilms      string                 `protobuf:"bytes,12,opt,name=total_films,json=totalFilms,proto3" json:"total_films,omitempty"`
	MovieCollection map[int32]*Movie       `protobuf:"bytes,13,rep,name=movie_collection,json=movieCollection,proto3" json:"movie_collection,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_proto_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{16}
}

func (x *Person) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Person) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Person) GetEnFullName() string {
	if x != nil {
		return x.EnFullName
	}
	return ""
}

func (x *Person) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *Person) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *Person) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Person) GetGrowth() string {
	if x != nil {
		return x.Growth
	}
	return ""
}

func (x *Person) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *Person) GetDeath() string {
	if x != nil {
		return x.Death
	}
	return ""
}

func (x *Person) GetCareer() string {
	if x != nil {
		return x.Career
	}
	return ""
}

func (x *Person) GetGenres() string {
	if x != nil {
		return x.Genres
	}
	return ""
}

func (x *Person) GetTotalFilms() string {
	if x != nil {
		return x.TotalFilms
	}
	return ""
}

func (x *Person) GetMovieCollection() map[int32]*Movie {
	if x != nil {
		return x.MovieCollection
	}
	return nil
}

type ReviewUserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewUserData) Reset() {
	*x = ReviewUserData{}
	mi := &file_proto_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewUserData) ProtoMessage() {}

func (x *ReviewUserData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewUserData.ProtoReflect.Descriptor instead.
func (*ReviewUserData) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{17}
}

func (x *ReviewUserData) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ReviewUserData) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	ReviewText    string                 `protobuf:"bytes,3,opt,name=review_text,json=reviewText,proto3" json:"review_text,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	User          *ReviewUserData        `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_proto_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{18}
}

func (x *Review) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Review) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Review) GetReviewText() string {
	if x != nil {
		return x.ReviewText
	}
	return ""
}

func (x *Review) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Review) GetUser() *ReviewUserData {
	if x != nil {
		return x.User
	}
	return nil
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x12\vuserservice\x1a\x1bgoogle/protobuf/empty.proto\"&\n" +
	"\x0eGetUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"8\n" +
	"\x0fGetUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.userservice.UserR\x04user\":\n" +
	"\x11CreateUserRequest\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.userservice.UserR\x04user\"E\n" +
	"\fLoginRequest\x125\n" +
	"\n" +
	"login_data\x18\x01 \x01(\v2\x16.userservice.LoginDataR\tloginData\")\n" +
	"\x11DeleteUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"W\n" +
	"\x11UpdateUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12,\n" +
	"\bnew_user\x18\x02 \x01(\v2\x11.userservice.UserR\anewUser\"\xae\x01\n" +
	"\x17UpdateUserAvatarRequest\x12\x1d\n" +
	"\n" +
	"upload_dir\x18\x01 \x01(\tR\tuploadDir\x12,\n" +
	"\x12hashed_avatar_name\x18\x02 \x01(\tR\x10hashedAvatarName\x12\x1f\n" +
	"\vavatar_file\x18\x03 \x01(\fR\n" +
	"avatarFile\x12%\n" +
	"\x04user\x18\x04 \x01(\v2\x11.userservice.UserR\x04user\")\n" +
	"\x11GetProfileRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"D\n" +
	"\x12GetProfileResponse\x12.\n" +
	"\aprofile\x18\x01 \x01(\v2\x14.userservice.ProfileR\aprofile\"G\n" +
	"\x14FavoriteMovieRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\"G\n" +
	"\x14FavoriteActorRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\"\xb1\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12'\n" +
	"\x0fhashed_password\x18\x06 \x01(\tR\x0ehashedPassword\"\x96\x02\n" +
	"\aProfile\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12=\n" +
	"\x10movie_collection\x18\x05 \x03(\v2\x12.userservice.MovieR\x0fmovieCollection\x12+\n" +
	"\x06actors\x18\x06 \x03(\v2\x13.userservice.PersonR\x06actors\x12-\n" +
	"\areviews\x18\a \x03(\v2\x13.userservice.ReviewR\areviews\"C\n" +
	"\tLoginData\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"s\n" +
	"\fRegisterData\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12+\n" +
	"\x11repeated_password\x18\x03 \x01(\tR\x10repeatedPassword\"\xa5\x01\n" +
	"\x05Movie\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vpreview_url\x18\x03 \x01(\tR\n" +
	"previewUrl\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12!\n" +
	"\frelease_date\x18\x05 \x01(\tR\vreleaseDate\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x01R\x06rating\"\xdd\x03\n" +
	"\x06Person\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12 \n" +
	"\fen_full_name\x18\x03 \x01(\tR\n" +
	"enFullName\x12\x14\n" +
	"\x05photo\x18\x04 \x01(\tR\x05photo\x12\x14\n" +
	"\x05about\x18\x05 \x01(\tR\x05about\x12\x10\n" +
	"\x03sex\x18\x06 \x01(\tR\x03sex\x12\x16\n" +
	"\x06growth\x18\a \x01(\tR\x06growth\x12\x1a\n" +
	"\bbirthday\x18\b \x01(\tR\bbirthday\x12\x14\n" +
	"\x05death\x18\t \x01(\tR\x05death\x12\x16\n" +
	"\x06career\x18\n" +
	" \x01(\tR\x06career\x12\x16\n" +
	"\x06genres\x18\v \x01(\tR\x06genres\x12\x1f\n" +
	"\vtotal_films\x18\f \x01(\tR\n" +
	"totalFilms\x12S\n" +
	"\x10movie_collection\x18\r \x03(\v2(.userservice.Person.MovieCollectionEntryR\x0fmovieCollection\x1aV\n" +
	"\x14MovieCollectionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.userservice.MovieR\x05value:\x028\x01\">\n" +
	"\x0eReviewUserData\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\"\x9f\x01\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1f\n" +
	"\vreview_text\x18\x03 \x01(\tR\n" +
	"reviewText\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12/\n" +
	"\x04user\x18\x05 \x01(\v2\x1b.userservice.ReviewUserDataR\x04user2\xc4\x06\n" +
	"\vUserService\x12D\n" +
	"\aGetUser\x12\x1b.userservice.GetUserRequest\x1a\x1c.userservice.GetUserResponse\x12D\n" +
	"\n" +
	"CreateUser\x12\x1e.userservice.CreateUserRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\x05Login\x12\x19.userservice.LoginRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\n" +
	"DeleteUser\x12\x1e.userservice.DeleteUserRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\n" +
	"UpdateUser\x12\x1e.userservice.UpdateUserRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x10UpdateUserAvatar\x12$.userservice.UpdateUserAvatarRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\n" +
	"GetProfile\x12\x1e.userservice.GetProfileRequest\x1a\x1f.userservice.GetProfileResponse\x12M\n" +
	"\x10AddFavoriteMovie\x12!.userservice.FavoriteMovieRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x10AddFavoriteActor\x12!.userservice.FavoriteActorRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x13RemoveFavoriteMovie\x12!.userservice.FavoriteMovieRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x13RemoveFavoriteActor\x12!.userservice.FavoriteActorRequest\x1a\x16.google.protobuf.EmptyB\aZ\x05./;pbb\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_user_proto_goTypes = []any{
	(*GetUserRequest)(nil),          // 0: userservice.GetUserRequest
	(*GetUserResponse)(nil),         // 1: userservice.GetUserResponse
	(*CreateUserRequest)(nil),       // 2: userservice.CreateUserRequest
	(*LoginRequest)(nil),            // 3: userservice.LoginRequest
	(*DeleteUserRequest)(nil),       // 4: userservice.DeleteUserRequest
	(*UpdateUserRequest)(nil),       // 5: userservice.UpdateUserRequest
	(*UpdateUserAvatarRequest)(nil), // 6: userservice.UpdateUserAvatarRequest
	(*GetProfileRequest)(nil),       // 7: userservice.GetProfileRequest
	(*GetProfileResponse)(nil),      // 8: userservice.GetProfileResponse
	(*FavoriteMovieRequest)(nil),    // 9: userservice.FavoriteMovieRequest
	(*FavoriteActorRequest)(nil),    // 10: userservice.FavoriteActorRequest
	(*User)(nil),                    // 11: userservice.User
	(*Profile)(nil),                 // 12: userservice.Profile
	(*LoginData)(nil),               // 13: userservice.LoginData
	(*RegisterData)(nil),            // 14: userservice.RegisterData
	(*Movie)(nil),                   // 15: userservice.Movie
	(*Person)(nil),                  // 16: userservice.Person
	(*ReviewUserData)(nil),          // 17: userservice.ReviewUserData
	(*Review)(nil),                  // 18: userservice.Review
	nil,                             // 19: userservice.Person.MovieCollectionEntry
	(*emptypb.Empty)(nil),           // 20: google.protobuf.Empty
}
var file_proto_user_proto_depIdxs = []int32{
	11, // 0: userservice.GetUserResponse.user:type_name -> userservice.User
	11, // 1: userservice.CreateUserRequest.user:type_name -> userservice.User
	13, // 2: userservice.LoginRequest.login_data:type_name -> userservice.LoginData
	11, // 3: userservice.UpdateUserRequest.new_user:type_name -> userservice.User
	11, // 4: userservice.UpdateUserAvatarRequest.user:type_name -> userservice.User
	12, // 5: userservice.GetProfileResponse.profile:type_name -> userservice.Profile
	15, // 6: userservice.Profile.movie_collection:type_name -> userservice.Movie
	16, // 7: userservice.Profile.actors:type_name -> userservice.Person
	18, // 8: userservice.Profile.reviews:type_name -> userservice.Review
	19, // 9: userservice.Person.movie_collection:type_name -> userservice.Person.MovieCollectionEntry
	17, // 10: userservice.Review.user:type_name -> userservice.ReviewUserData
	15, // 11: userservice.Person.MovieCollectionEntry.value:type_name -> userservice.Movie
	0,  // 12: userservice.UserService.GetUser:input_type -> userservice.GetUserRequest
	2,  // 13: userservice.UserService.CreateUser:input_type -> userservice.CreateUserRequest
	3,  // 14: userservice.UserService.Login:input_type -> userservice.LoginRequest
	4,  // 15: userservice.UserService.DeleteUser:input_type -> userservice.DeleteUserRequest
	5,  // 16: userservice.UserService.UpdateUser:input_type -> userservice.UpdateUserRequest
	6,  // 17: userservice.UserService.UpdateUserAvatar:input_type -> userservice.UpdateUserAvatarRequest
	7,  // 18: userservice.UserService.GetProfile:input_type -> userservice.GetProfileRequest
	9,  // 19: userservice.UserService.AddFavoriteMovie:input_type -> userservice.FavoriteMovieRequest
	10, // 20: userservice.UserService.AddFavoriteActor:input_type -> userservice.FavoriteActorRequest
	9,  // 21: userservice.UserService.RemoveFavoriteMovie:input_type -> userservice.FavoriteMovieRequest
	10, // 22: userservice.UserService.RemoveFavoriteActor:input_type -> userservice.FavoriteActorRequest
	1,  // 23: userservice.UserService.GetUser:output_type -> userservice.GetUserResponse
	20, // 24: userservice.UserService.CreateUser:output_type -> google.protobuf.Empty
	20, // 25: userservice.UserService.Login:output_type -> google.protobuf.Empty
	20, // 26: userservice.UserService.DeleteUser:output_type -> google.protobuf.Empty
	20, // 27: userservice.UserService.UpdateUser:output_type -> google.protobuf.Empty
	20, // 28: userservice.UserService.UpdateUserAvatar:output_type -> google.protobuf.Empty
	8,  // 29: userservice.UserService.GetProfile:output_type -> userservice.GetProfileResponse
	20, // 30: userservice.UserService.AddFavoriteMovie:output_type -> google.protobuf.Empty
	20, // 31: userservice.UserService.AddFavoriteActor:output_type -> google.protobuf.Empty
	20, // 32: userservice.UserService.RemoveFavoriteMovie:output_type -> google.protobuf.Empty
	20, // 33: userservice.UserService.RemoveFavoriteActor:output_type -> google.protobuf.Empty
	23, // [23:34] is the sub-list for method output_type
	12, // [12:23] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
