// Code generated by MockGen. DO NOT EDIT.
// Source: collection_handler.go

// Package delivery_mocks is a generated GoMock package.
package delivery_mocks

import (
	context "context"
	reflect "reflect"

	mocks "github.com/go-park-mail-ru/2025_1_sigmaScript/internal/server/mocks"
	gomock "github.com/golang/mock/gomock"
)

// MockCollectionServiceInterface is a mock of CollectionServiceInterface interface.
type MockCollectionServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionServiceInterfaceMockRecorder
}

// MockCollectionServiceInterfaceMockRecorder is the mock recorder for MockCollectionServiceInterface.
type MockCollectionServiceInterfaceMockRecorder struct {
	mock *MockCollectionServiceInterface
}

// NewMockCollectionServiceInterface creates a new mock instance.
func NewMockCollectionServiceInterface(ctrl *gomock.Controller) *MockCollectionServiceInterface {
	mock := &MockCollectionServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCollectionServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionServiceInterface) EXPECT() *MockCollectionServiceInterfaceMockRecorder {
	return m.recorder
}

// GetMainPageCollections mocks base method.
func (m *MockCollectionServiceInterface) GetMainPageCollections(ctx context.Context) (mocks.Collections, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMainPageCollections", ctx)
	ret0, _ := ret[0].(mocks.Collections)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMainPageCollections indicates an expected call of GetMainPageCollections.
func (mr *MockCollectionServiceInterfaceMockRecorder) GetMainPageCollections(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMainPageCollections", reflect.TypeOf((*MockCollectionServiceInterface)(nil).GetMainPageCollections), ctx)
}
