server:
  address: main_server
  port: 8080
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 30s
  idle_timeout: 60s

cookie:
  session_name: "session_id"
  session_length: 32
  http_only: true
  secure: false
  # SameSiteDefaultMode = 1
  # SameSiteLaxMode = 2
  # SameSiteStrictMode = 3
  # SameSiteNoneMode = 4
  same_site: 3
  path: "/"
  expiration_age: -1

database:
  host: filmlk_db
  port: 5432
  user: "filmlk_user"
  password: "filmlk_password"
  dbname: "filmlk"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 300s
  conn_max_idle_time: 60s

storage:
  relative_path: "/static/avatars/"


