server:
  address: localhost
  port: 8080
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 30s
  idle_timeout: 60s

cookie:
  session_name: "session_id"
  session_length: 32
  http_only: true
  secure: false
  # SameSiteDefaultMode = 1
  # SameSiteLaxMode = 2
  # SameSiteStrictMode = 3
  # SameSiteNoneMode = 4
  same_site: 3
  path: "/"
  reset_max_age: -1
