// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package mocks

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks(in *jlexer.Lexer, out *WatchProviderJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "logo_url":
			out.Logo = string(in.String())
		case "movie_url":
			out.Url = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks(out *jwriter.Writer, in WatchProviderJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"logo_url\":"
		out.RawString(prefix)
		out.String(string(in.Logo))
	}
	{
		const prefix string = ",\"movie_url\":"
		out.RawString(prefix)
		out.String(string(in.Url))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WatchProviderJSON) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WatchProviderJSON) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WatchProviderJSON) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WatchProviderJSON) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks(l, v)
}
func easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks1(in *jlexer.Lexer, out *ReviewUserDataJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "login":
			out.Login = string(in.String())
		case "avatar":
			out.Avatar = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks1(out *jwriter.Writer, in ReviewUserDataJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix[1:])
		out.String(string(in.Login))
	}
	if in.Avatar != "" {
		const prefix string = ",\"avatar\":"
		out.RawString(prefix)
		out.String(string(in.Avatar))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReviewUserDataJSON) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReviewUserDataJSON) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReviewUserDataJSON) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReviewUserDataJSON) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks1(l, v)
}
func easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks2(in *jlexer.Lexer, out *ReviewJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "score":
			out.Score = float64(in.Float64())
		case "review_text":
			out.ReviewText = string(in.String())
		case "created_at":
			out.CreatedAt = string(in.String())
		case "user":
			(out.User).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks2(out *jwriter.Writer, in ReviewJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"score\":"
		out.RawString(prefix)
		out.Float64(float64(in.Score))
	}
	{
		const prefix string = ",\"review_text\":"
		out.RawString(prefix)
		out.String(string(in.ReviewText))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix)
		(in.User).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReviewJSON) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReviewJSON) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReviewJSON) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReviewJSON) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks2(l, v)
}
func easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks3(in *jlexer.Lexer, out *NewReviewDataJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "review_text":
			out.ReviewText = string(in.String())
		case "score":
			out.Score = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks3(out *jwriter.Writer, in NewReviewDataJSON) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	if in.ReviewText != "" {
		const prefix string = ",\"review_text\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ReviewText))
	}
	{
		const prefix string = ",\"score\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.Score))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NewReviewDataJSON) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NewReviewDataJSON) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NewReviewDataJSON) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NewReviewDataJSON) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks3(l, v)
}
func easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks4(in *jlexer.Lexer, out *MovieJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "original_name":
			out.OriginalName = string(in.String())
		case "about":
			out.About = string(in.String())
		case "poster":
			out.Poster = string(in.String())
		case "promo_url":
			out.PromoURL = string(in.String())
		case "release_year":
			out.ReleaseYear = string(in.String())
		case "country":
			out.Country = string(in.String())
		case "slogan":
			out.Slogan = string(in.String())
		case "director":
			out.Director = string(in.String())
		case "budget":
			out.Budget = int64(in.Int64())
		case "box_office_us":
			out.BoxOfficeUS = int64(in.Int64())
		case "box_office_global":
			out.BoxOfficeGlobal = int64(in.Int64())
		case "box_office_russia":
			out.BoxOfficeRussia = int64(in.Int64())
		case "premier_russia":
			out.PremierRussia = string(in.String())
		case "premier_global":
			out.PremierGlobal = string(in.String())
		case "rating":
			out.Rating = float64(in.Float64())
		case "duration":
			out.Duration = string(in.String())
		case "genres":
			out.Genres = string(in.String())
		case "staff":
			if in.IsNull() {
				in.Skip()
				out.Staff = nil
			} else {
				in.Delim('[')
				if out.Staff == nil {
					if !in.IsDelim(']') {
						out.Staff = make([]PersonJSON, 0, 0)
					} else {
						out.Staff = []PersonJSON{}
					}
				} else {
					out.Staff = (out.Staff)[:0]
				}
				for !in.IsDelim(']') {
					var v1 PersonJSON
					(v1).UnmarshalEasyJSON(in)
					out.Staff = append(out.Staff, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "reviews":
			if in.IsNull() {
				in.Skip()
				out.Reviews = nil
			} else {
				in.Delim('[')
				if out.Reviews == nil {
					if !in.IsDelim(']') {
						out.Reviews = make([]ReviewJSON, 0, 0)
					} else {
						out.Reviews = []ReviewJSON{}
					}
				} else {
					out.Reviews = (out.Reviews)[:0]
				}
				for !in.IsDelim(']') {
					var v2 ReviewJSON
					(v2).UnmarshalEasyJSON(in)
					out.Reviews = append(out.Reviews, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "rating_kp":
			out.RatingKP = float64(in.Float64())
		case "rating_imdb":
			out.RatingIMDB = float64(in.Float64())
		case "watchability":
			if in.IsNull() {
				in.Skip()
				out.Watchability = nil
			} else {
				in.Delim('[')
				if out.Watchability == nil {
					if !in.IsDelim(']') {
						out.Watchability = make([]WatchProviderJSON, 0, 1)
					} else {
						out.Watchability = []WatchProviderJSON{}
					}
				} else {
					out.Watchability = (out.Watchability)[:0]
				}
				for !in.IsDelim(']') {
					var v3 WatchProviderJSON
					(v3).UnmarshalEasyJSON(in)
					out.Watchability = append(out.Watchability, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "logo":
			out.Logo = string(in.String())
		case "backdrop":
			out.Backdrop = string(in.String())
		case "similar_movies":
			if in.IsNull() {
				in.Skip()
				out.SimilarMovies = nil
			} else {
				in.Delim('[')
				if out.SimilarMovies == nil {
					if !in.IsDelim(']') {
						out.SimilarMovies = make([]Movie, 0, 0)
					} else {
						out.SimilarMovies = []Movie{}
					}
				} else {
					out.SimilarMovies = (out.SimilarMovies)[:0]
				}
				for !in.IsDelim(']') {
					var v4 Movie
					(v4).UnmarshalEasyJSON(in)
					out.SimilarMovies = append(out.SimilarMovies, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks4(out *jwriter.Writer, in MovieJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	if in.OriginalName != "" {
		const prefix string = ",\"original_name\":"
		out.RawString(prefix)
		out.String(string(in.OriginalName))
	}
	if in.About != "" {
		const prefix string = ",\"about\":"
		out.RawString(prefix)
		out.String(string(in.About))
	}
	if in.Poster != "" {
		const prefix string = ",\"poster\":"
		out.RawString(prefix)
		out.String(string(in.Poster))
	}
	if in.PromoURL != "" {
		const prefix string = ",\"promo_url\":"
		out.RawString(prefix)
		out.String(string(in.PromoURL))
	}
	if in.ReleaseYear != "" {
		const prefix string = ",\"release_year\":"
		out.RawString(prefix)
		out.String(string(in.ReleaseYear))
	}
	if in.Country != "" {
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		out.String(string(in.Country))
	}
	if in.Slogan != "" {
		const prefix string = ",\"slogan\":"
		out.RawString(prefix)
		out.String(string(in.Slogan))
	}
	if in.Director != "" {
		const prefix string = ",\"director\":"
		out.RawString(prefix)
		out.String(string(in.Director))
	}
	if in.Budget != 0 {
		const prefix string = ",\"budget\":"
		out.RawString(prefix)
		out.Int64(int64(in.Budget))
	}
	if in.BoxOfficeUS != 0 {
		const prefix string = ",\"box_office_us\":"
		out.RawString(prefix)
		out.Int64(int64(in.BoxOfficeUS))
	}
	if in.BoxOfficeGlobal != 0 {
		const prefix string = ",\"box_office_global\":"
		out.RawString(prefix)
		out.Int64(int64(in.BoxOfficeGlobal))
	}
	if in.BoxOfficeRussia != 0 {
		const prefix string = ",\"box_office_russia\":"
		out.RawString(prefix)
		out.Int64(int64(in.BoxOfficeRussia))
	}
	if in.PremierRussia != "" {
		const prefix string = ",\"premier_russia\":"
		out.RawString(prefix)
		out.String(string(in.PremierRussia))
	}
	if in.PremierGlobal != "" {
		const prefix string = ",\"premier_global\":"
		out.RawString(prefix)
		out.String(string(in.PremierGlobal))
	}
	if in.Rating != 0 {
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Float64(float64(in.Rating))
	}
	if in.Duration != "" {
		const prefix string = ",\"duration\":"
		out.RawString(prefix)
		out.String(string(in.Duration))
	}
	if in.Genres != "" {
		const prefix string = ",\"genres\":"
		out.RawString(prefix)
		out.String(string(in.Genres))
	}
	if len(in.Staff) != 0 {
		const prefix string = ",\"staff\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v5, v6 := range in.Staff {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.Reviews) != 0 {
		const prefix string = ",\"reviews\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v7, v8 := range in.Reviews {
				if v7 > 0 {
					out.RawByte(',')
				}
				(v8).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.RatingKP != 0 {
		const prefix string = ",\"rating_kp\":"
		out.RawString(prefix)
		out.Float64(float64(in.RatingKP))
	}
	if in.RatingIMDB != 0 {
		const prefix string = ",\"rating_imdb\":"
		out.RawString(prefix)
		out.Float64(float64(in.RatingIMDB))
	}
	if len(in.Watchability) != 0 {
		const prefix string = ",\"watchability\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v9, v10 := range in.Watchability {
				if v9 > 0 {
					out.RawByte(',')
				}
				(v10).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Logo != "" {
		const prefix string = ",\"logo\":"
		out.RawString(prefix)
		out.String(string(in.Logo))
	}
	if in.Backdrop != "" {
		const prefix string = ",\"backdrop\":"
		out.RawString(prefix)
		out.String(string(in.Backdrop))
	}
	if len(in.SimilarMovies) != 0 {
		const prefix string = ",\"similar_movies\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v11, v12 := range in.SimilarMovies {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MovieJSON) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MovieJSON) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MovieJSON) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MovieJSON) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks4(l, v)
}
func easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks5(in *jlexer.Lexer, out *GenreJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks5(out *jwriter.Writer, in GenreJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GenreJSON) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GenreJSON) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2ba5d8eEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GenreJSON) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GenreJSON) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2ba5d8eDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks5(l, v)
}
