// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package mocks

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF6a71b2aDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks(in *jlexer.Lexer, out *PersonJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "full_name":
			out.FullName = string(in.String())
		case "en_full_name":
			out.EnFullName = string(in.String())
		case "photo":
			out.Photo = string(in.String())
		case "about":
			out.About = string(in.String())
		case "sex":
			out.Sex = string(in.String())
		case "growth":
			out.Growth = string(in.String())
		case "birthday":
			out.Birthday = string(in.String())
		case "death":
			out.Death = string(in.String())
		case "career":
			out.Career = string(in.String())
		case "genres":
			out.Genres = string(in.String())
		case "total_films":
			out.TotalFilms = string(in.String())
		case "movie_collection":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.MovieCollection = make(Collection)
				} else {
					out.MovieCollection = nil
				}
				for !in.IsDelim('}') {
					key := int(in.IntStr())
					in.WantColon()
					var v1 Movie
					(v1).UnmarshalEasyJSON(in)
					(out.MovieCollection)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF6a71b2aEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks(out *jwriter.Writer, in PersonJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"full_name\":"
		out.RawString(prefix)
		out.String(string(in.FullName))
	}
	if in.EnFullName != "" {
		const prefix string = ",\"en_full_name\":"
		out.RawString(prefix)
		out.String(string(in.EnFullName))
	}
	{
		const prefix string = ",\"photo\":"
		out.RawString(prefix)
		out.String(string(in.Photo))
	}
	if in.About != "" {
		const prefix string = ",\"about\":"
		out.RawString(prefix)
		out.String(string(in.About))
	}
	if in.Sex != "" {
		const prefix string = ",\"sex\":"
		out.RawString(prefix)
		out.String(string(in.Sex))
	}
	if in.Growth != "" {
		const prefix string = ",\"growth\":"
		out.RawString(prefix)
		out.String(string(in.Growth))
	}
	if in.Birthday != "" {
		const prefix string = ",\"birthday\":"
		out.RawString(prefix)
		out.String(string(in.Birthday))
	}
	if in.Death != "" {
		const prefix string = ",\"death\":"
		out.RawString(prefix)
		out.String(string(in.Death))
	}
	if in.Career != "" {
		const prefix string = ",\"career\":"
		out.RawString(prefix)
		out.String(string(in.Career))
	}
	if in.Genres != "" {
		const prefix string = ",\"genres\":"
		out.RawString(prefix)
		out.String(string(in.Genres))
	}
	if in.TotalFilms != "" {
		const prefix string = ",\"total_films\":"
		out.RawString(prefix)
		out.String(string(in.TotalFilms))
	}
	if len(in.MovieCollection) != 0 {
		const prefix string = ",\"movie_collection\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.MovieCollection {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.IntStr(int(v2Name))
				out.RawByte(':')
				(v2Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PersonJSON) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF6a71b2aEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PersonJSON) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF6a71b2aEncodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PersonJSON) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF6a71b2aDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PersonJSON) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF6a71b2aDecodeGithubComGoParkMailRu20251SigmaScriptInternalServerMocks(l, v)
}
