version: '3'

services:
  db:
    build:
      dockerfile: postgres.Dockerfile
    container_name: filmlk_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-filmlk}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: [ 'CMD-SHELL', "sh -c 'pg_isready -U service_user -d ${POSTGRES_DB:-filmlk}'" ]
      interval: 2s
      timeout: 3s
      retries: 3
    networks:
      - filmlk-net # Add the shared network

volumes:
  db_data:


networks:
  filmlk-net:
    external:
      name: filmlk-net
